Nest table func
FCO/Cromponent pull request #4
Opened 2024-12-09 17:29 UTC by librasteve

export lib components as functions

2024-12-09 17:30 UTC, librasteve commented
resolves issue #1

2024-12-09 18:09 UTC, FCO requested changes

2024-12-09 18:09 UTC, FCO commented on README.md
> +[![Actions Status](https://github.com/librasteve/Cromponent/actions/workflows/test.yml/badge.svg)](https://github.com/librasteve/Cromponent/actions)
This seems to be pointing to the wrong repo

2024-12-09 18:09 UTC, FCO commented on bin/nest-table-func.raku
> +        html :lang<en>, [
Sorry, I don't see the point of mixing cro templates and HTML::Functional... what's the point?

2024-12-09 21:29 UTC, librasteve commented on bin/nest-table-func.raku
> +        html :lang<en>, [
good question ;-)

I like that raku is both OO and functional capable. On the functional side, this means that raku is a good alternative to the functional development of websites pioneered by Elm language (elm is front end, raku is back end so we also need htmx or similar)

Here's a post I made on the topic...
https://rakujourney.wordpress.com/2024/10/27/raku-htmlfunctional/ 

The intersect with components is that - where folks make crotmp components (and I hope we make a lot ;-)), then they can be consumed with either other Cro Templates or in a functional way:

# Template Way

```
my $table = Table.new: [[1,2],[3,4]];

template-with-components Q:to/END/, { :$table };
<html>
	<head>
		<script src="https://unpkg.com/htmx.org@2.0.3"></script>
	</head>
	<body>
		<&Table(.table)>
	</body>
</html>


```

#Functional Way

```
my $template = 
  html :lang<en>, [
      head [ script :src<https://unpkg.com/htmx.org@2.0.3"> ],
      body [
          mytable $[[1, 2], [3, 4]], :$topic;
      ]
  ];

template-with-components $template, $topic;
```

Me, I am a big fan of the functional ... it's hard to see the real power in a short example, so I ask you to squint and imagine this with 100s lines HTML.

So, I am hoping that you will agree that this at least this is a timtowdi and that it would be cool for the Cromponent that we write to be useable in both ways ;-)

2024-12-16 10:16 UTC, librasteve commented
also resolves issue #5

2024-12-20 12:15 UTC, closed without merging